{% set name = "CoinMP" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.coin-or.org/download/source/CoinMP/{{ name }}-{{ version }}.zip
  sha256: a87c451bf7d4d77aa81c3e6b6b7220fd3ca9fe8e16e303b2e6aeded02cce00ed

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - pkgconfig
    - readline
    - zlib
    - bzip2
  run:
    - readline
    - zlib
    - bzip2

test:
  commands:
    - cbc ?
    - clp ?

about:
  home: http://www.coin-or.org/
  license: CPL 1.0
  license_file: LICENSE
  summary: The Computational Infrastructure for Operations Research
  description: The Computational Infrastructure for Operations Research
  doc_url: http://www.coin-or.org/faqs.html#ObtainSrcCode
  dev_url: http://subversion.tigris.org

extra:
  recipe-maintainers:
    - bgruening
