appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hrRJ2Jh4NrjQsE/YSPknOxGPpvRJZWSCYt72hWuhk/9FcW7jtMjwsL/PIXBdMgpZPdNv0ZBkCHSPTCL14SSHS2sdRsBI8f/N4inAsJRXNK0ICNYWX6xG5GxUdTy5n03QJrzQ+81dhNmBSWHZNVdbxf7pvTCxtzCd0EV2m81wrKWzrVbFwfkRPYV6VP1ib0vmRLb1jCOgMl9imClsWPTDsaXTXbcHWinZhuW6Rz08QV25IiKqf2kGvoNtgkhoCR0jxV1PaKuwdFaqX9prCRCwZgKGQ1ga6dr27TDOoYf4yRRPA+b6Kmw9jWeiq6P69KmX6YNKyGZQDb+1sireCWCKo+MHY3OprTaxyDEIJq8hRsqHaIe2ii8hYUKdArMnBGR7XsMNC+oSqBlnX0ulrN6r5jQ6VDyQHaZb0j3AvwN6ttgO2CfvEzbIgTg74Fj9uZ1H5cOI0DB0BZ0z4PY5tevVtddnOGwgRzDjOG+5Rmxu0QoVkP9iZfg2Mp4C6xUFa9A2HIEHdmwEYdtRF1ULbgoImfCdoq6eWCGBTk2lhiuYoa1XAz9SosI4GqyfYyPpRvb9KhJj8jGwBi9AwHlta3cvvXuyl5/UrbJgL78eW6T6gTTrMa9D2rruuNBvxaQFhDYwvoaPTBMYVHGt/PLXCuwJFqnv5sBUnNB3hGHOqt6zCA8=}
